name: EssenceCore
version: 1.0.0
main: com.essencecore.EssenceCore
api-version: '1.21'
author: EssenceCore
description: Highly customizable essence system with unique powers
softdepend: [Vault, PlayerPoints, PlaceholderAPI]

commands:
  essence:
    description: Main essence command
    usage: /essence <give|remove|list|reload> [player] [essence]
    permission: essence.admin
    aliases: [ess, essences]

permissions:
  essence.admin:
    description: Access to all essence commands
    default: op
  essence.use:
    description: Allows using essence abilities
    default: true